############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Call for Papers"
url = "/cfp"
weight = 2

[[main]]
name = "Instructions"
weight = 3

[[main]]
parent = "Instructions"
name = "Submission guidelines"
url = "/submission_guidelines"

[[main]]
parent = "Instructions"
name = "Review guidelines"
url = "/review_guidelines"

[[main]]
name = "Schedule"
url = "/schedule"
weight = 4

[[main]]
name = "Proceedings"
url = "/proceedings"
weight = 5

[[main]]
name = "Organizers"
url = "/organizers"
weight = 6

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Call for Papers"
url = "/cfp"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3

