############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Editions"
url = "/editions"
weight = 2

[[main]]
name = "News"
url = "/blog"
weight = 3

[[main]]
name = "People"
url = "/authors"
weight = 4

[[main]]
name = "Contact"
url = "/contact"
weight = 5


# footer menu
[[footer]]
name = "Editions"
url = "/editions"
weight = 1

[[footer]]
name = "Contact"
url = "/contact"
weight = 2
